app/mod_file/controllers.py
from flask import Blueprint, request, render_template
from flask import flash, redirect, url_for, abort
from app.mod_file.forms import FileForm
from flask_login import login_required
from flask_login import current_user
from app import db
import uuid
from werkzeug.utils import secure_filename
from app.mod_link.models import Link
import os
import app
from urllib.parse import urlparse
import zipfile


mod_file = Blueprint('file', __name__, url_prefix='/files')


@mod_file.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = FileForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            starting_directory = os.getcwd()
            zipfile_name = f'{str(uuid.uuid4())}.zip'
            os.chdir(app.app.config['UPLOAD_FILE_DIRECTORY'])

            with zipfile.ZipFile(zipfile_name, mode='w') as archive:
                for f in form.photo.data:
                    filename = secure_filename(f.filename)

                    f.save(filename)
                    archive.write(filename)
                    os.remove(filename)

            os.chdir(starting_directory)

            file_url = f"{app.app.config['SHARED_FILES_BASE_URL']}/{zipfile_name}"

            link = Link(original_url=file_url,
                        visits_allowed=form.visits_allowed.data,
                        unique_id=str(uuid.uuid4()),
                        user_id=current_user.id,
                        comment=form.comment.data)
            db.session.add(link)
            db.session.commit()
            return redirect(url_for('link.link', link_id=link.id))
        else:
            flash('Form not validated')
    return render_template('files/upload.html', form=form)

app/templates/files/upload.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Upload a New File {% endblock %}</h1>

<form method="post" enctype="multipart/form-data" action="{{ url_for('file.upload') }}">
    {{ form.csrf_token }}

    <div class="form-group">
      <label for="amount">File</label>
      {{ form.photo(class="form-control")  }}
      <small id="photoHelp" class="form-text text-muted">Photo</small>
    </div>

    <div class="form-group">
      <label for="amount">Visits Allowed</label>
      {{ form.visits_allowed(size=20, class="form-control")  }}
      <small id="allowedVisitsHelp" class="form-text text-muted">The number of times someone is allowed to click link.</small>
    </div>

    <div class="form-group">
      <label for="amount">Comment</label>
      {{ form.comment(size=256, class="form-control")  }}
      <small id="commentHelp" class="form-text text-muted">Additional information about this link.</small>
    </div>

    <input type="submit" class="btn btn-primary" value="Upload">
    <a href="{{url_for('link.index')}}" class="btn btn-primary" role="button">Cancel</a>
</form>
{% endblock %}