app/mod_link/controllers.py
from flask import Blueprint, request, render_template
from flask import flash, redirect, url_for, abort
from app.mod_link.forms import LinkForm
from app.mod_link.forms import LinkDeleteForm
from app.mod_link.models import Link
from flask_login import login_required
from flask_login import current_user
from app import db
from sqlalchemy import desc
from datetime import datetime
import uuid


mod_link = Blueprint('link', __name__, url_prefix='/links')


@mod_link.route('/')
@login_required
def index():
    links = Link.query.order_by(desc('created_at')).all()

    return render_template('links/index.html', links=links)


@mod_link.route('/<int:link_id>')
@login_required
def link(link_id):
    link = Link.query.get(link_id)
    if link is None:
        abort(404)
    form = LinkDeleteForm()
    return render_template('links/show.html', form=form, link=link)


@mod_link.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = LinkForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            link = Link(original_url=form.original_url.data,
                        visits_allowed=form.visits_allowed.data,
                        unique_id=str(uuid.uuid4()),
                        user_id=current_user.id,
                        comment=form.comment.data)
            db.session.add(link)
            db.session.commit()
            return redirect(url_for('link.index'))
        else:
            flash('Form not validated')
    return render_template('links/create.html', form=form)


@mod_link.route('/delete', methods=['POST'])
@login_required
def delete():
    form = LinkDeleteForm()
    link = Link.query.get(form.link_id.data)
    if form.validate_on_submit():
        if link is not None:
            for click in link.clicks:
                db.session.delete(click)
            db.session.delete(link)
            db.session.commit()
        return redirect(url_for('link.index'))
    else:
        flash('Failed to delete link')
    return render_template('links/show.html', form=form, link=link)


@mod_link.route('/reset/<id>', methods=['GET'])
@login_required
def reset(id):
    link = Link.query.get(id)
    if link is not None:
        link.visits_used = 0
        link.is_available = True
        link.updated_at = datetime.utcnow()
        db.session.add(link)
        db.session.commit()
    else:
        flash('Failed to reset link')
    return redirect(url_for('link.link', link_id=link.id))

app/templates/links/create.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Create a New Link {% endblock %}</h1>

<form method="post" action="{{ url_for('link.create') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      <label for="payer_name">Original URL</label>
      {{ form.original_url(size=256, class="form-control")  }}
      <small id="originalUrlHelp" class="form-text text-muted">The original link.</small>
    </div>

    <div class="form-group">
      <label for="amount">Visits Allowed</label>
      {{ form.visits_allowed(size=20, class="form-control")  }}
      <small id="allowedVisitsHelp" class="form-text text-muted">The number of times someone is allowed to click link.</small>
    </div>

    <div class="form-group">
      <label for="amount">Comment</label>
      {{ form.comment(size=256, class="form-control")  }}
      <small id="commentHelp" class="form-text text-muted">Additional information about this link.</small>
    </div>

    <input type="submit" class="btn btn-primary" value="Create">
    <a href="{{url_for('link.index')}}" class="btn btn-primary" role="button">Cancel</a>
</form>
{% endblock %}

app/templates/links/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Links {% endblock %}</h1>

    <ol>
        {% for link in links %}
        <li>
            <a href="{{ url_for('link.link', link_id=link.id) }}">
            <ul>
                <li>{{ link['comment'] }}</li>
                <li>Still Available? {{ link['is_available'] }}</li>
                <li>Created At: {{ link['created_at'] }}</li>
            </ul>
            </a>
        </li>
        {% endfor %}
    </ol>
{% endblock %}

app/templates/links/show.html
{% extends 'base.html' %}

{% block content %}
    <script>
      function confirm_delete(form) {
        var r = confirm("Are you sure?");
        if (r == true) {
          document.forms["delete_link"].submit();
        }
      }
    </script>
<ul>
    <li>Original URL: {{ link['original_url'] }}</li>
    <li>Unique URL: {{ url_for('deliver_link', unique_id=link['unique_id'], _external=True) }}</li>
    <li>Visits Allowed: {{ link['visits_allowed'] }}</li>
    <li>Visits Used: {{ link['visits_used'] }}</li>
    <li>Is Still Available? {{ link['is_available'] }}</li>
    <li>Created At: {{ link['created_at'] }}</li>
    <li>Updated At: {{ link['updated_at'] }}</li>
    <li>Comment: {{ link['comment'] }}</li>
</ul>

<form method="post" action="{{ url_for('link.delete') }}" name="delete_link">
    {{ form.csrf_token }}
    {{ form.link_id(value=link['id']) }}
    <a onclick="window.history.back();" class="btn btn-link" role="button">Back</a>
    <a href="{{ url_for('link.reset', id=link.id) }}" class="btn btn-link" role="button">Reset</a>
    <a onclick="confirm_delete();" class="btn btn-danger" role="button">Delete</a>
</form>

<hr />
<h4>Clicks</h4>

<ol>
  {% for click in link.clicks %}
  <li>
      <ul>
          <li>Clicked From: {{ click['ip_address'] }}</li>
          <li>Clicked At: {{ click.local_timestamp() }}</li>
          <li>Link Available? {{ click.was_available }}</li>
      </ul>
  </li>
  {% endfor %}
</ol>

{% endblock %}