app/mod_auth/controllers.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from app import login_manager
from app.mod_auth.forms import LoginForm
from app.mod_auth.models import User
from werkzeug.exceptions import abort
from flask_login import login_required, login_user, logout_user
from urllib.parse import urlparse, urljoin
import hashlib


mod_auth = Blueprint('auth', __name__, url_prefix='/auth')


def get_user(user_form):
    username = user_form.username.data
    password = user_form.password.data
    hashed_password = hashlib.sha512(password.encode('utf-8')).hexdigest()
    user = User.query.filter_by(username=username,
                                password=hashed_password).first()
    return user


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and (ref_url.netloc ==
                                                     test_url.netloc)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = get_user(form)
        if user is None:
            flash('Login failed', category='error')
            return redirect('/')
        login_user(user)
        flash('Logged in successfully.', category='success')
        next = request.args.get('next')
        if not is_safe_url(next):
            return abort(400)

        return redirect(next or url_for('index'))
    return render_template('auth/login.html', form=form)


@mod_auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Logged out successfully.', category='success')
    return redirect(url_for('index'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-md navbar-light bg-light">
          <a class="navbar-brand" href="{{ url_for('index')}}">LUL</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              {% if current_user.is_authenticated %}
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{{
                            url_for('file.upload') }}">New File</a>
                </li>                  
                <li class="nav-item active">
                        <a class="nav-link" href="{{
                                url_for('link.create') }}">New Link</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('link.index') }}">Links</a>
                  </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a class="nav-link" href=#>Hi, {{ current_user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                </ul>
              {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                </ul>
              {% endif %}
          </div>
      </nav>
      <div class="container">
          {% for message in get_flashed_messages(with_categories=True) %}
            {% if message[0] == 'success' %}
              <div class="alert alert-success">{{ message[1] }}</div>
            {% else %}
              <div class="alert alert-danger">{{ message[1] }}</div>
            {% endif %}
          {% endfor %}
          {% block content %} {% endblock %}
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Limited Use Links {% endblock %}</h1>

{% endblock %}
:wa